# Generated by Django 2.0.4 on 2018-04-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
