# Generated by Django 2.0.4 on 2018-04-26 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authiz', '0002_client_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
