# Generated by Django 2.0.4 on 2018-04-30 05:45

from django.db import migrations, models
import localized_fields.fields.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.field.LocalizedField(required=['ru', 'en', 'ky'], uniqueness=[])),
            ],
        ),
    ]
