# Generated by Django 2.0.4 on 2018-04-30 05:47

from django.db import migrations
import localized_fields.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=localized_fields.fields.char_field.LocalizedCharField(required=['ru', 'en', 'ky'], uniqueness=[]),
        ),
    ]
