# Generated by Django 2.0.4 on 2018-04-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180430_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
