# Generated by Django 2.0.4 on 2018-04-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180430_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='title_ru',
        ),
    ]
