# Generated by Django 2.0.4 on 2018-04-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_test_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
