# Generated by Django 2.0.4 on 2018-04-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_test_title_ru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
