# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180430_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='title_ky',
            new_name='title_kk',
        ),
    ]
