# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180430_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
