# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0014_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(help_text='О клинике', verbose_name='О клинике')),
                ('youtube_vid', embed_video.fields.EmbedVideoField(help_text='Например: https://www.youtube.com/watch?v=oBT4FR84PSg', verbose_name='Видео на ютубе')),
                ('vision', models.TextField(verbose_name='Видение')),
                ('mission', models.TextField(verbose_name='Миссия')),
                ('philosophy', models.TextField(verbose_name='Наша философия')),
            ],
        ),
    ]
