# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_en',
            field=models.TextField(help_text='О клинике', null=True, verbose_name='О клинике'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_kk',
            field=models.TextField(help_text='О клинике', null=True, verbose_name='О клинике'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_ru',
            field=models.TextField(help_text='О клинике', null=True, verbose_name='О клинике'),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_en',
            field=models.TextField(null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_kk',
            field=models.TextField(null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_ru',
            field=models.TextField(null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='about',
            name='philosophy_en',
            field=models.TextField(null=True, verbose_name='Наша философия'),
        ),
        migrations.AddField(
            model_name='about',
            name='philosophy_kk',
            field=models.TextField(null=True, verbose_name='Наша философия'),
        ),
        migrations.AddField(
            model_name='about',
            name='philosophy_ru',
            field=models.TextField(null=True, verbose_name='Наша философия'),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_en',
            field=models.TextField(null=True, verbose_name='Видение'),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_kk',
            field=models.TextField(null=True, verbose_name='Видение'),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_ru',
            field=models.TextField(null=True, verbose_name='Видение'),
        ),
    ]
