# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180430_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Фамилия, Имя, Отчество', max_length=120, verbose_name='ФИО')),
                ('fullname_ru', models.CharField(help_text='Фамилия, Имя, Отчество', max_length=120, null=True, verbose_name='ФИО')),
                ('fullname_en', models.CharField(help_text='Фамилия, Имя, Отчество', max_length=120, null=True, verbose_name='ФИО')),
                ('fullname_kk', models.CharField(help_text='Фамилия, Имя, Отчество', max_length=120, null=True, verbose_name='ФИО')),
                ('specialty', models.CharField(help_text='Должность', max_length=120, verbose_name='Напишите его должность')),
                ('specialty_ru', models.CharField(help_text='Должность', max_length=120, null=True, verbose_name='Напишите его должность')),
                ('specialty_en', models.CharField(help_text='Должность', max_length=120, null=True, verbose_name='Напишите его должность')),
                ('specialty_kk', models.CharField(help_text='Должность', max_length=120, null=True, verbose_name='Напишите его должность')),
                ('about', models.TextField(verbose_name='Видение')),
                ('about_ru', models.TextField(null=True, verbose_name='Видение')),
                ('about_en', models.TextField(null=True, verbose_name='Видение')),
                ('about_kk', models.TextField(null=True, verbose_name='Видение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
            ],
        ),
    ]
