# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=120, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=120, null=True, verbose_name='Адрес')),
                ('address_kk', models.CharField(max_length=120, null=True, verbose_name='Адрес')),
                ('telephones', models.CharField(help_text='Напишите все номера через запитой, например: 996 702 12-34-56, 996 702 12-34-56', max_length=120, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=120, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=60)),
                ('symbol', models.CharField(help_text='Доступные соцети: vk, odnoklassniki, facebook, twitter, instagram', max_length=13)),
            ],
        ),
    ]
