# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contact_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='symbol',
            field=models.CharField(help_text='Доступные соцети: facebook, instagram, youtube', max_length=13),
        ),
    ]
