# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180430_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
