# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 09:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180430_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephones',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, help_text='Напишите все номера через запитой, например: 996 702 12-34-56, 996 702 12-34-56', max_length=10, verbose_name='Номер телефона'), size=8), size=8),
        ),
    ]
