# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180430_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephones',
            field=models.CharField(help_text='Напишите все номера через запитой, например: 996 702 12-34-56, 996 702 12-34-56', max_length=120, verbose_name='Номер телефона'),
        ),
    ]
