# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180430_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(verbose_name='Описание')),
                ('treatment_inner', models.TextField(verbose_name='Что входит в эту услугу:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatments')),
            ],
        ),
    ]
