# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='body_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='title_kk',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_inner_en',
            field=models.TextField(null=True, verbose_name='Что входит в эту услугу:'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_inner_kk',
            field=models.TextField(null=True, verbose_name='Что входит в эту услугу:'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_inner_ru',
            field=models.TextField(null=True, verbose_name='Что входит в эту услугу:'),
        ),
    ]
