# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180502_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
