# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180502_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiagnostica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Категория')),
                ('name_ru', models.CharField(max_length=60, null=True, verbose_name='Категория')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='Категория')),
                ('name_kk', models.CharField(max_length=60, null=True, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(verbose_name='Описание')),
                ('diag_inner', models.TextField(verbose_name='Что входит в эту услугу:')),
                ('diag_more', models.TextField(verbose_name='При проведении:')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnostics')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CategoryDiagnostica', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='UnderCategoryDiagnostica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='По категория')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CategoryDiagnostica', verbose_name='Категория')),
            ],
        ),
        migrations.AlterField(
            model_name='treatment',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
