# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180502_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='undercategorydiagnostica',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='По категория'),
        ),
        migrations.AddField(
            model_name='undercategorydiagnostica',
            name='name_kk',
            field=models.CharField(max_length=60, null=True, verbose_name='По категория'),
        ),
        migrations.AddField(
            model_name='undercategorydiagnostica',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='По категория'),
        ),
    ]
