# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180502_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='body_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='diag_inner_en',
            field=models.TextField(null=True, verbose_name='Что входит в эту услугу:'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='diag_inner_kk',
            field=models.TextField(null=True, verbose_name='Что входит в эту услугу:'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='diag_inner_ru',
            field=models.TextField(null=True, verbose_name='Что входит в эту услугу:'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='diag_more_en',
            field=models.TextField(null=True, verbose_name='При проведении:'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='diag_more_kk',
            field=models.TextField(null=True, verbose_name='При проведении:'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='diag_more_ru',
            field=models.TextField(null=True, verbose_name='При проведении:'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='title_kk',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
    ]
